rules:
  unpinned-uses:
    config:
      policies:
        Homebrew/actions/*: ref-pin
  dangerous-triggers:
    ignore:
      - publish.yml
      - triage.yml
  unpinned-images:
    ignore:
      - dispatch-build-bottle.yml:97
      - tests.yml:95
