name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

env:
  HOMEBREW_ARM64_TESTING: 1
  HOMEBREW_DEVELOPER: 1

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  check-syntax:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: false
          test-bot: true

      - name: Check out Pull Request
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check syntax
        run: brew test-bot --only-tap-syntax

  setup-matrix:
    runs-on: ubuntu-latest
    needs: check-syntax
    permissions:
      contents: read
      pull-requests: read
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false

      - name: Set up matrix
        id: setup-matrix
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
        with:
          script: |
            const fs = require('fs');

            const runners = fs.readFileSync('./.github/runners.json');
            let matrix = JSON.parse(runners);

            const request = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })

            console.log(request.data);
            const labels = request.data.labels.map(label => label.name);
            console.log(labels);
            if (labels.length) {
              if (labels.includes("macos only")) {
                matrix = matrix.filter(runner => runner.runs_on !== "ubuntu-22.04");
              }
            }

            console.log(JSON.stringify(matrix));
            core.setOutput('matrix', JSON.stringify({ include: matrix }));

  tests:
    needs: setup-matrix
    permissions:
      contents: read
      pull-requests: read
    strategy:
      matrix: ${{fromJson(needs.setup-matrix.outputs.matrix)}}
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}
    container: ${{ matrix.container && matrix.container != '' && matrix.container || null }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.working_directory || github.workspace }}
    env:
      BOTTLES_DIR: ${{ matrix.working_directory || github.workspace }}/bottles
    steps:
      - name: Pre-test steps
        uses: Homebrew/actions/pre-build@master
        with:
          bottles-directory: ${{ env.BOTTLES_DIR }}
          cleanup: ${{ matrix.cleanup_before }}

      - run: brew test-bot --only-formulae --root-url='https://ghcr.io/v2/bevanjkay/homebrew-formulae'
        id: brew-test-bot-formulae
        if: github.event_name == 'pull_request'
        working-directory: ${{ env.BOTTLES_DIR }}

      - name: Post-build steps
        if: >
          github.event_name == 'pull_request' &&
          !contains(fromJson('["skipped", "cancelled"]'), steps.brew-test-bot-formulae.conclusion)
        uses: Homebrew/actions/post-build@master
        with:
          bottles-directory: ${{ env.BOTTLES_DIR }}
          logs-directory: ${{ format('{0}/logs', env.BOTTLES_DIR) }}
          runner: ${{ matrix.runs_on }}
          cleanup: false
