name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check PR Labels
      id: check-pr-labels
      if: github.event_name == 'pull_request'
      run: |
        gh pr view "${{ github.event.pull_request.number }}" --json 'labels' | jq -r '.labels[].name' > labels.txt
        echo "labels=$(cat labels.txt)" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Set up matrix
      id: setup-matrix
      uses: actions/github-script@v7
      with:
        script: |    
          try {
            const fs = require('fs');
            const runners = fs.readFileSync('./.github/runners.json');
            let matrix = JSON.parse(runners);

            const labels = JSON.parse("[" + process.env.labels + "]");

            if (labels.includes("macos only")) {
              matrix = matrix.filter(runner => runner.runs_on !== "ubuntu-22.04");
            }
            console.log(JSON.stringify(matrix));
          } catch (error) {
            core.setFailed(error.message);
          }  

    - name: Debug
      run: echo ${{ steps.setup-matrix.outputs.matrix }}  
  
  tests:
    needs: setup-matrix
    strategy:
      matrix: ${{fromJson(needs.setup-matrix.outputs.matrix)}}
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}
    container: ${{ matrix.container || '' }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.working_directory || github.workspace }}
    env:
      BOTTLES_DIR: ${{ matrix.working_directory || github.workspace }}/bottles
    steps:
      - name: Pre-test steps
        uses: Homebrew/actions/pre-build@master
        with:
          bottles-directory: ${{ env.BOTTLES_DIR }}
          cleanup: ${{ matrix.cleanup_before }}

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae --root-url='https://ghcr.io/v2/bevanjkay/homebrew-formulae'
        id: brew-test-bot-formulae
        if: github.event_name == 'pull_request'
        working-directory: ${{ env.BOTTLES_DIR }}

      - name: Post-build steps
        if: >
          github.event_name == 'pull_request' &&
          !contains(fromJson('["skipped", "cancelled"]'), steps.brew-test-bot-formulae.conclusion)
        uses: Homebrew/actions/post-build@master
        with:
          bottles-directory: ${{ env.BOTTLES_DIR }}
          logs-directory: ${{ format('{0}/logs', env.BOTTLES_DIR) }}
          runner: ${{ matrix.runs_on }}
          cleanup: false